steps:
  test:
    depends_on: []
    image: ${IMAGE}
    when:
      event: [tag, push]
    environment:
      - CARGO_TERM_COLOR=always
      - CARGO_BUILD_TARGET=${TARGET}
    commands:
      - ${PACKAGE_MANAGER} update
      - ${PACKAGE_MANAGER} ${INSTALL_CMD} -q ${PACKAGE}
      - rustup default stable
      - rustup target add ${TARGET}
      - rustup component add clippy
      - cargo test
      - cargo clippy

  build:
    depends_on: []
    image: ${IMAGE}
    when:
      event: tag
    environment:
      - CARGO_TERM_COLOR=always
      - CARGO_BUILD_TARGET=${TARGET}
    commands:
      - ${PACKAGE_MANAGER} update
      - ${PACKAGE_MANAGER} ${INSTALL_CMD} -q ${PACKAGE}
      - rustup default stable
      - rustup target add ${TARGET}
      - cargo build --profile optimized
      - tar -zcvf kiss-rs-${TARGET}.tar.gz target/${TARGET}/optimized/kiss

  publish:
    depends_on: [test, build]
    image: woodpeckerci/plugin-gitea-release
    when:
      event: tag
    settings:
      base_url: https://codeberg.org
      files:
        - "kiss-rs-${TARGET}.tar.gz"
      file-exists: overwrite
      api_key:
        from_secret: CODEBERG_ACCESS_TOKEN
      target: main
      title: kiss-rs
      skip_verify: true

## only x86_64-unknown-linux-{musl, gnu} are enabled for now
matrix:
  include:
    ## musl
    - IMAGE: rust:alpine
      TARGET: x86_64-unknown-linux-musl
      PACKAGE_MANAGER: apk
      INSTALL_CMD: add
      PACKAGE: musl-dev
    # - IMAGE: rust:alpine
    #   TARGET: aarch64-unknown-linux-musl
    #   PACKAGE_MANAGER: apk
    #   INSTALL_CMD: add
    #   PACKAGE: "gcc-aarch64-none-elf musl-dev binutils-aarch64"
    #   CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-none-elf-gcc
    ## gnu/glibc
    - IMAGE: rust:latest
      TARGET: x86_64-unknown-linux-gnu
      PACKAGE_MANAGER: apt
      INSTALL_CMD: install
      PACKAGE: gcc
    # - IMAGE: rust:latest
    #   TARGET: aarch64-unknown-linux-gnu
    #   PACKAGE_MANAGER: apt
    #   INSTALL_CMD: "install -y"
    #   PACKAGE: "gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu"
    #   CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    # - TARGET: x86_64-pc-windows-gnu
    #   IMAGE: rust:latest
    #   PACKAGE: windows/amd64
    # - TARGET: x86_64-pc-windows-msvc
    #   IMAGE: rust:latest
    #   PACKAGE: windows/amd64
