[package]
name = "kiss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
## cli
seahorse = "2.1"
termcolor = "1.2.0"
## lazy initizalize variables
once_cell = "1.17.0"
## tar extraction
tar = "0.4"
xz2 = "0.1"
zstd = "0.12"
bzip2 = "0.4"
flate2 = "1.0"
## checksum
blake3 = "1.4.0"
hex = "0.4"
## downloads
ureq = { version = "2.7.0", features = [ "default" ] }
## signal handling
nix = { version = "0.26.1", default-features = false, features = [ "signal" ] }

[profile.release]
lto = "thin"

[profile.optimized]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
opt-level = 3
