[package]
name = "kiss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dumb_terminal = ["colored/no-color"]

[dependencies]
## cli
seahorse = "2.1"
colored = "2"
## parallel
## rayon = "1.7.0"
once_cell = "1.17.0"
## num_cpus = "1.15.0"
## tar extraction
tar = "0.4"
xz2 = "0.1"
zstd = "0.12"
bzip2 = "0.4"
flate2 = "1.0"
## checksum
blake3 = "1.4.0"
hex = "0.4"
## downloads
reqwest = { version = "0.11", features = [ "default" ] }
tokio = { version = "1", features = ["full"] }
## signal handling
ctrlc = "3.4"

[profile.release]
lto = "thin"

[profile.optimized]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
opt-level = 3
