[package]
name = "kiss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dumb_terminal = ["colored/no-color"]

[dependencies]
## cli
seahorse = "2.1"
colored = "2"
## parallel
rayon = "1.7.0"
once_cell = "1.17.0"
num_cpus = "1.15.0"
## archive
#decompress = "0.5"
## checksum
blake3 = "1.4.0"
hex = "0.4"
## downloads
#reqwest = { version = "0.11", features = ["default", "gzip"] }

[profile.release]
lto = "thin"

[profile.optimized]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
opt-level = 3
