[package]
name = "kiss"
version = "0.1.0"
edition = "2021"
authors = ["XDream8 <WolfsDream@proton.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/XDream8/kiss-rs"
description = "An implementation of kiss package manager in rust"

[dependencies]
## cli
seahorse = "2.1"
termcolor = "1.2.0"
## lazy initizalize variables
once_cell = "1.17.0"
## tar extraction
tar = "0.4.38"
xz2 = "0.1.7"
zstd = "0.12"
bzip2 = "0.4.4"
flate2 = "1.0.26"
## checksum
blake3 = { version = "1.4.0", default-features = false }
hex = "0.4"
## downloads
ureq = { version = "2.7.0", features = [ "default" ] }
## signal handling
nix = { version = "0.26.1", default-features = false, features = [ "signal" ] }

[profile.release]
lto = "thin"

[profile.optimized]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
opt-level = 3
